import Head from 'next/head'
import { codeInspirations } from '../../.next/lib/data';

export default function BlogPage({ title, date, content }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{title}</h1>
        <p>{date}</p>
        <p>{content}</p>
      </main>

    </div>
  )
}

export async function getStaticProps(context) {
  console.log("hue", context);
  const { params } = context;
  return {
    props: codeInspirations.find(item => item.slug === params.slug), // will be passed to the page component as props
  }
}

export async function getStaticPaths() {
  return {
    paths: codeInspirations.map((item) => ({
      params: {
        slug: item.slug,
      },
    })),
    fallback: false, // See the "fallback" section below
  };
}