import Head from "next/head";
import React, { useEffect } from 'react'; 
import { getAllSnippets } from "../../lib/data";
import { format, parseISO } from "date-fns";
import { serialize } from "next-mdx-remote/serialize";
import { MDXRemote } from "next-mdx-remote";
const prism = require("prismjs")
require('prismjs/components/prism-python');


export default function BlogPage({ title, date, content }) {
  
  useEffect(() => {
    if (typeof window !== "undefined") {
      prism.highlightAll();
    }
  }, []);

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="border-b-2 border-gray-200 mb-4">
          <h2 className="text-3xl font-bold">{title}</h2>
          <div className="text-gray-600 text-md">
            {format(parseISO(date), "do MMMM, uuu")}
          </div>
        </div>
        <div className="prose">
          <MDXRemote {...content} />
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  const { params } = context;
  const allSnippets = getAllSnippets();
  const { data, content } = allSnippets.find(
    (item) => item.slug === params.slug
  ); // will be passed to the page component as props
  const mdxSource = await serialize(content);

  return {
    props: {
      ...data,
      date: data.date.toISOString(),
      content: mdxSource,
    },
  };
}

export async function getStaticPaths() {
  return {
    paths: getAllSnippets().map((post) => ({
      params: {
        slug: post.slug,
      },
    })),
    fallback: false, // See the "fallback" section below
  };
}
