import Head from 'next/head'
import { getAllSnippets } from '../../lib/data';
import { format, parseISO } from 'date-fns';

export default function BlogPage({ title, date, content }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div className="border-b-2 border-gray-200 mb-4">
          <h2 className="text-3xl font-bold">{title}</h2>
          <div className="text-gray-600 text-md">
            {format(parseISO(date), 'do MMMM, uuu')}
          </div>
        </div>
        <div className="prose">{content}</div>
      </main>

    </div>
  )
}

export async function getStaticProps(context) {
  const { params } = context;
  const allSnippets = getAllSnippets();
  const { data, content } = allSnippets.find((item) => item.slug === params.slug) // will be passed to the page component as props

  return {
    props:  {
      ...data,
      date: data.date.toISOString(),
      content, 
    }
  }
}

export async function getStaticPaths() {

  return {
    paths: getAllSnippets().map((post) => ({
      params: {
        slug: post.slug,
      },
    })),
    fallback: false, // See the "fallback" section below
  };
}