import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>100 code inspirations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>100 code inspirations</h1>
      </main>

    </div>
  )
}
