import Head from "next/head";
import Link from "next/Link";
import { format, parseISO } from "date-fns";
import { getAllSnippets } from '../lib/data'

export default function Home({ snippets }) {
  return (
    <div>
      <Head>
        <title>100 code inspirations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="space-y-4">
        {snippets.map(item => (
          <CodeInspirationItem key={item.slug} {...item} />
        ))}
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const allSnippets = getAllSnippets();

  return {
    props: {
      snippets: allSnippets.map(({ data, content, slug }) => ({
        ...data,
        description: data.description,
        date: data.date.toISOString(),
        content,
        slug
      })),
    },
  };
}

function CodeInspirationItem({ slug, title, date, description }) {
  return (
    <div
      className="border border-gray-100 shadow hover:shadow-md hover:border-gray-200 rounded-md p-4 transition duration-200 ease-in"
      key={slug}
    >
      <div>
        <Link href={`/blog/${slug}`}>
          <a className="font-bold">{title}</a>
        </Link>
      </div>
      <div className="text-grey-600 text-xs">
        <p>{format(parseISO(date), "do MMMM, uuu")}</p>
      </div>
      <p>{description}</p>
    </div>
  );
}
